/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_jnitool_JNITool */

#ifndef _Included_com_demo_jnitool_JNITool
#define _Included_com_demo_jnitool_JNITool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_jnitool_JNITool
 * Method:    decrypt
 * Signature: (Ljava/lang/String;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_demo_jnitool_JNITool_decrypt
  (JNIEnv *, jclass, jstring, jbyteArray);

/*
 * Class:     com_demo_jnitool_JNITool
 * Method:    unShell
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_demo_jnitool_JNITool_unShell
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_demo_jnitool_JNITool
 * Method:    checkey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_demo_jnitool_JNITool_checkey
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
